server:
  port: 10000  #启动端口
spring:
  files:
    yamlFiles:
      - dataId: nanjing.yml
        group: DEFAULT_GROUP
    branches:
      - master
      - wwj
      - dev
      - test
      - release
    gogsToken: 83d583f4cf65c78bedbbeaf234bb0f104b5b7d38
  application:
    name: nacos-manager
  cloud:
    nacos:
      discovery:
        server-addr: http://192.168.137.1:8848
        metadata:
          version: '@version@'
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
        file-extension: yaml
        name: nacos-manager
gogs:
  server: 127.0.0.1:3000
nacos:
  server: 192.168.137.1:8848
